# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-04 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='about',
            new_name='reference_title',
        ),
        migrations.RemoveField(
            model_name='home',
            name='ajuda',
        ),
        migrations.RemoveField(
            model_name='home',
            name='exames',
        ),
    ]
