# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-04 20:04
from __future__ import unicode_literals

import builtins
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20171104_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='reference_title',
            new_name='about',
        ),
        migrations.AddField(
            model_name='home',
            name='ajuda',
            field=models.TextField(default=builtins.dir),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='exames',
            field=models.TextField(default=datetime.datetime(2017, 11, 4, 20, 4, 19, 271058, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
