# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_generic_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='about',
        ),
        migrations.RemoveField(
            model_name='home',
            name='ajuda',
        ),
        migrations.RemoveField(
            model_name='home',
            name='exames',
        ),
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
        migrations.AddField(
            model_name='home',
            name='home_content',
            field=models.ManyToManyField(to='about.Generic_content'),
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_cardio',
        ),
        migrations.AddField(
            model_name='about',
            name='about_cardio',
            field=models.ManyToManyField(to='about.Generic_content'),
        ),
        migrations.RemoveField(
            model_name='generic_content',
            name='generic_content',
        ),
        migrations.AddField(
            model_name='generic_content',
            name='generic_content',
            field=models.ManyToManyField(to='about.Paragraph'),
        ),
    ]
