# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('version', models.TextField(max_length=50)),
                ('release_date', models.TimeField(verbose_name='Ultimate Release')),
                ('about_cardio', models.TextField()),
            ],
        ),
    ]
