# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-15 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20171109_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.TextField()),
                ('phone', models.TextField()),
                ('contac_content', models.ManyToManyField(to='about.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_title', models.TextField(max_length=50)),
                ('help_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='generic_content',
            name='generic_content',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_cardio',
        ),
        migrations.RemoveField(
            model_name='about',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='about_content',
            field=models.ManyToManyField(to='about.Paragraph'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_title',
            field=models.TextField(default=datetime.datetime(2017, 11, 15, 18, 23, 51, 812044, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='home_title',
            field=models.TextField(default=datetime.datetime(2017, 11, 15, 18, 24, 16, 401615, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='home_content',
            field=models.ManyToManyField(to='about.Paragraph'),
        ),
        migrations.DeleteModel(
            name='Generic_content',
        ),
    ]
