# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Generic_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_title', models.TextField(max_length=50)),
                ('generic_content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='examn',
            name='examns',
            field=models.ManyToManyField(to='charts.Generic_content'),
        ),
    ]
