# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='generic_content',
            name='generic_content',
        ),
        migrations.AddField(
            model_name='generic_content',
            name='generic_content',
            field=models.ManyToManyField(to='charts.Paragraph'),
        ),
    ]
