# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-15 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20171106_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic_content',
            name='generic_content',
        ),
        migrations.RemoveField(
            model_name='examn',
            name='examns',
        ),
        migrations.AddField(
            model_name='examn',
            name='examn_content',
            field=models.ManyToManyField(to='charts.Paragraph'),
        ),
        migrations.AddField(
            model_name='examn',
            name='examn_title',
            field=models.TextField(default=datetime.datetime(2017, 11, 15, 13, 18, 6, 555880, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Generic_content',
        ),
    ]
